### ISSUE TITLE
Not working in android 11 devices

### ISSUE THREAD

**Issue by kgsnaidu** [mdrajibsk8/react-native-device-number#1]
It could be due to security changes in version 11

https://developer.android.com/about/versions/11/privacy/permissions#phone-numbers

**Comment by Ujjalcha1** [comment]
It works perfectly on Android 11 Please check your code



![WhatsApp Image 2021-05-17 at 5 20 22 PM](https://user-images.githubusercontent.com/40722840/118484220-d7cbb500-b6cb-11eb-9371-ff77fe4a756a.jpeg)

**Comment by hemaljoshi** [comment]
@Ujjalcha1 which version of the library you have used please tell me
