### ISSUE TITLE
Could not create task ':react-native-device-number:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by bibekk-mss** [mdrajibsk8/react-native-device-number#12]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tasks'.
> Could not create task ':react-native-device-number:compileDebugJavaWithJavac'.
   > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

 "react": "18.2.0",
 "react-native": "0.72.3",

    "react-native-device-number": "^1.0.7",

**Comment by mdrajibsk8** [comment]
Fixed in v1.0.9
