### ISSUE TITLE
After adding this code, popup of mobile number selection is not displaying.

### ISSUE THREAD

**Issue by coolvaibhav** [mdrajibsk8/react-native-device-number#2]
I have added the your code in my project, but not able to extract the mobile number

I have aded below files at below location android/app/src/main/java/com/xxx/yyy/
DeviceNumberActivity.java
DeviceNumberModule.java
DeviceNumberPackage.java

android/app/src/main/res/layout/
activity_device_number.xml

not able to extract mobile number, please guide me to fix it. if anything is missing please let me know

**Comment by mdrajibsk8** [comment]
Try to install the package & follow the doc or the video. It will work. thanks
