### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by livaios** [mdrajibsk8/react-native-device-number#3]
I am trying it and I am getting the following error
{"line":234233,"column":49,"sourceURL":"http://192.168.0.159:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&minify=false"}

**Comment by mdrajibsk8** [comment]
It does not support expo. Try to use React native CLI. thanks

**Comment by manjunath-nuveb** [comment]
@mdrajibsk8  will it work if expo is ejected?
