### ISSUE TITLE
App is being closed automatically & [Error: Cancle]

### ISSUE THREAD

**Issue by hemaljoshi** [mdrajibsk8/react-native-device-number#6]
app is being closed automatically

react-native: 0.61.3
library version: 1.0.7
In android version: 10 there is "[Error: Cancle]"
in android Version: 12 app is being closed automatically 

one question library supports emulator or not?

**Comment by AgustinSantillan** [comment]
Hello, good afternoon, I have the same problem, did you find any solution? Do you know if there is another way to get the phone number?

**Comment by hemaljoshi** [comment]
@AgustinSantillan No resolution on this

**Comment by rabindrachhachan** [comment]
I have the same problem. I don't think this library support android 11 and above.

**Comment by alejocor** [comment]
> 

Did you resolved this?

**Comment by mdrajibsk8** [comment]
Fixed in v1.0.9
