### ISSUE TITLE
Module DeviceNumber requires main queue setup

### ISSUE THREAD

**Issue by RRaideRR** [mdrajibsk8/react-native-device-number#8]
Thanks for the library. It's doing a great job. I noticed a warning on startup but it doesn't break any things (at least none that I observed)

`Module DeviceNumber requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of`

**Comment by amitsonit** [comment]
I have same issue, On IOS its just break the code.

**Comment by mdrajibsk8** [comment]
IOS support is not enable yet.
